#Saved properties: server
#Sun Jun 28 15:35:56 CEST 2026
maxConnections=100
name=StorageServer-1
passwordHash=$2a$12$V9ol//Vn3tQjRRD9xAr8kOfIjJiYI3zPltKjJ9JV/oF9JxnU3BZFi
port=6700
storagePath=storage1
