#Saved properties: server
#Sun Jun 28 17:16:10 CEST 2026
maxConnections=100
name=StorageServer-2
passwordHash=$2a$12$A8TD8bwC57ZMil/AORCzo.9NCE5r52lQuRjJxSh73lG5JZae8rJR6
port=6701
storagePath=storage2
